stages:
  - test
  - build
  - image
  - chart
  - deploy

variables:
  APP: goid
  IMAGE_HOST: ccr.ccs.tencentyun.com
  IMAGE_USERNAME: 100003612951
  IMAGE_PASSWORD: 002b373aea22247d
  IMAGE: jormin/$APP
  IMAGE_TAG: v1.0.${CI_PIPELINE_IID}
  IMAGE_ADDRESS: $IMAGE_HOST/$IMAGE:$IMAGE_TAG
  ARGOCD_SERVER: argocd.wcxst.com
  ARGOCD_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkMGM0MmI4MC01NGM4LTRhNDAtYmZiNi0xYjExZTFiN2I0ZjUiLCJpYXQiOjE2MzcxNjIxMjksImlzcyI6ImFyZ29jZCIsIm5iZiI6MTYzNzE2MjEyOSwic3ViIjoiYWRtaW46YXBpS2V5In0.bTunYzbtfoRODOtV3pdYdi3OpWBbpCUrr4-eeurTGQY
go-test:
  stage: test
  before_script:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.io,direct
    - go mod download
  script:
    - go test -v ./...
  only:
    - master

go-build:
  stage: build
  before_script:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY=https://goproxy.io,direct
    - go mod download
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o $APP main.go
  artifacts:
    paths:
      - $APP
    expire_in: 1h
  only:
    - master

make-image:
  stage: image
  dependencies:
    - go-build
  script:
    - docker login $IMAGE_HOST --username=$IMAGE_USERNAME --password=$IMAGE_PASSWORD
    - docker build -t $IMAGE_ADDRESS -f ./Dockerfile .
    - docker push $IMAGE_ADDRESS
  only:
    - master

make-deploy:
  stage: deploy
  script:
    - |
      # 修改 values.yaml 并提交 gitlab
      git clone ssh://git@gitlab.wcxst.com:2224/jormin/deploy.git && cd deploy
      sed -i "s#tag: \".*#tag: \"$IMAGE_TAG\"#" $APP/values.yaml
      git add . && git commit -m "${CI_COMMIT_MESSAGE} - ${CI_COMMIT_AUTHOR}"
      git push
      # argocd 同步
      ssh root@${ARGOCD_SERVER} "cd /data/deploy && git pull"
      ssh root@${ARGOCD_SERVER} "argocd app set $APP --auth-token $ARGOCD_TOKEN --server $ARGOCD_SERVER --values $APP/values.yaml --sync-option ApplyOutOfSyncOnly=true --grpc-web"
      ssh root@${ARGOCD_SERVER} "argocd app sync $APP --auth-token $ARGOCD_TOKEN --server $ARGOCD_SERVER --prune --grpc-web"
  only:
    - master
